name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main  # or whichever branch you're using for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.GCP_VM_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy files to VM
      run: |
        rsync -avz -e "ssh -i ~/.ssh/id_ed25519" --delete ./ \
        ${{ secrets.GCP_VM_USERNAME }}@${{ secrets.GCP_VM_HOST }}:/var/www/html

    - name: Run cache busting script on VM
      run: |
        ssh -i ~/.ssh/id_ed25519 ${{ secrets.GCP_VM_USERNAME }}@${{ secrets.GCP_VM_HOST }} \
        "cd /var/www/html && ./update_version.sh"

    - name: Restart web server
      run: |
        ssh -i ~/.ssh/id_ed25519 ${{ secrets.GCP_VM_USERNAME }}@${{ secrets.GCP_VM_HOST }} \
        "sudo systemctl restart nginx"
